version: '3.7'
services:
  mysqldb:
    image: "mysql/mysql-server:8.0.20"
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: '123'
        MYSQL_USER: 'empuser'
        MYSQL_PASS: 'password'
        MYSQL_DATABASE: 'profiles'
    volumes:
        - "${MYSQLDB_DATA}:/var/lib/mysql"
  
  profile-mvc:
    image: "leandrosantos/profile-mvc:latest"
    ports:
        - 8080:8080
    volumes:
        - "${PROFILE_MVC_DATA}:/data:rw"    